# Generated by Django 3.0.5 on 2020-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_solved',
            field=models.DateTimeField(null=True),
        ),
    ]
