# Generated by Django 3.0.5 on 2020-08-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prob',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prob.probTag'),
        ),
    ]
