# Generated by Django 3.0.5 on 2020-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlog',
            name='flag',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
